repos:
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.2.1
    hooks:
      - id: tofu_fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude_types: ["markdown"]
      - id: check-yaml
      - id: end-of-file-fixer
